# Generated by Django 3.0.1 on 2020-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Task Name')),
                ('priority', models.CharField(max_length=120)),
                ('duration', models.DurationField(max_length=60)),
                ('due_time', models.DateTimeField(verbose_name='Task Due Time')),
            ],
        ),
    ]
